// <auto-generated />
namespace CodeFirstApproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Designationadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Designationadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202201060236563_Designationadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
